obj-m += networkfs.o
networkfs-objs += entrypoint.o http.o inode.o file.o super.o
ccflags-y := -std=gnu11 -Wno-declaration-after-statement

all:
	make -C /lib/modules/$(shell uname -r)/build M=$(shell pwd) modules

clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(shell pwd) clean

